apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-backend
  template:
    metadata:
      labels:
        app: node-backend
    spec:
      containers:
        - name: node-backend
          image: waleedqazi/fullstack-node:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: mongodb://mongo.dev.svc.cluster.local:27017/devopsdb
---
apiVersion: v1
kind: Service
metadata:
  name: node-backend
  namespace: dev
spec:
  selector:
    app: node-backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: web
      port: 80
      targetPort: 3000
  type: NodePort

